FROM node:22-alpine

WORKDIR /app
#สร้าง Package
COPY package*.json ./
#ติดตั้ง Node module
RUN npm install
#จาก Client ไป App โดยจุดแรกจะอ้างอิงตัวหลัก และตัวที่สองเป็นการอ้างอิงกับตัว App หรือ โฟล์เดอร์
COPY . .

EXPOSE 5173
#npm run dev
CMD [ "npm", "run", "dev" ]