FROM node:22-alpine

WORKDIR /app
#สร้าง Package
COPY package*.json ./

#ติดตั้ง Node module
RUN npm install -g nodemon && npm install
#จาก Client ไป App โดยจุดแรกจะอ้างอิงตัวหลัก และตัวที่สองเป็นการอ้างอิงกับตัว App หรือ โฟล์เดอร์
COPY . .
#เปลี่ยน Port 
EXPOSE 5000

#npm start
CMD ["nodemon", "index.js"]